# Generated by Django 2.0.1 on 2019-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0002_auto_20190909_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=20, verbose_name='编码'),
        ),
    ]
