# Generated by Django 2.0.1 on 2019-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0003_auto_20190909_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
